### ISSUE TITLE
Session::spawn() method is hard to use across platforms

### ISSUE THREAD

**Issue by palant** [zhiburt/expectrl#33]
As things are now, `Session::spawn()` expects `std::process::Command` on Unix-like platforms and `conpty::ProcAttr` on Windows (the documentation only mentions the former). The API doesn’t expose the command type in use, this type is private. As a result, my code has to depend on `conpty` even though it doesn’t actually use it.

The way I see it, expectrl could at least expose the command type publicly. But ideally it would really take the standard `std::process::Command` structure on all platforms and convert to `conpty::ProcAttr` itself.

**Comment by palant** [comment]
More subtle differences: `std::process::Command::args()` takes anything that can be turned into an iterator, `conpty::ProcAttr::args()`. And while the former can be called any number of times to add arguments, the latter will replace the entire arguments list. It’s such a mess, I’d really prefer expectrl to handle `conpty` internally.

**Comment by zhiburt** [comment]
@palant it must be closed,

I'll try to improve the documentation a bit and will release this.

**Comment by zhiburt** [comment]
released in 0.4.0

Thank you bringing this issue up.
