### ISSUE TITLE
`interact()` seems consumes too much CPU 

### ISSUE THREAD

**Issue by yinheli** [zhiburt/expectrl#45]
Example, following example will cause 100% CPU usage.

```rust
fn main() {
    let shell = "bash";
    let mut sh = expectrl::spawn(shell.to_string()).expect("Error while spawning sh");

    println!("Connecting to {}", shell);

    sh.interact().unwrap();
}
```

**Comment by yinheli** [comment]
It seems `session.try_read` is non_blocking, So infinity loop consume too much CPU. Mybe should spawn new thread to do read & write separately.

**Comment by zhiburt** [comment]
> Example, following example will cause 100% CPU usage.

Interesting.
Good catch.

> It seems session.try_read is non_blocking, So infinity loop consume too much CPU. Mybe should spawn new thread to do read & write separately.

Right, because we need to check whether there's something in `stdin` and in `stdout`/`stderr` of a process.

> Mybe should spawn new thread to do read & write separately.

Maybe.
But there might some workaround.
I have something in mind.

**Comment by zhiburt** [comment]
Seems like I've managed it.
There's still some todos:

1. it doesn't yet work on windows.
2. wanna try to add an optional thread spawning as you've suggested.
3. the feature name may be changed in the future.

Do

```toml
expectrl = { git = "https://github.com/zhiburt/expectrl/", branch = "reduce_cpu_usage_in_interact", features = ["polling"] }
```

**Comment by zhiburt** [comment]
I want to highlight about your proposal with spawning a thread which will block on read.
It works.

But there's no easy way how to stop it.
I mean we can't stop it when it's blocked.

So the thread will became dangling.

**Comment by yinheli** [comment]
`interact` feature is too complex. especially you have std & async implements .

**Comment by zhiburt** [comment]
Good morning

> interact feature is too complex. especially you have std & async implements.

What do you mean?

**Comment by zhiburt** [comment]
Just wanted to let you know that I've just published the feature.
You can use `0.6.0` version.

It also brings changes to the interact interface.

**Comment by yinheli** [comment]
Thanks, It okay now.
