### ISSUE TITLE
Capture waidpid result in interact()

### ISSUE THREAD

**Issue by mitsuhiko** [zhiburt/expectrl#53]
Today when using `interact` the exit code is lost because `is_alive` will swallow it. It would be nice if the session could hold on to the `status()` so that it can be called again later to retrieve the first observed status.

**Comment by zhiburt** [comment]
Hi @mitsuhiko 

So what you're mentioned is true.
Do you think `is_alive` flag is enough or we better return the status flag from `waitpid`?

*I strive a bit to `bool` as windows doesn't have status flags (as far as I remember) so the interface would be the same.

ref: #

Take care.

**Comment by mitsuhiko** [comment]
For what I needed I actually need the entire return code since I need to know if it existed successfully or not. That said, I am currently not using this library because it turns out that some of the abstractions are actually not what I need.

**Comment by zhiburt** [comment]
> For what I needed I actually need the entire return code since I need to know if it existed successfully or not.

Make sense.
(I hope to merge soon)

> That said, I am currently not using this library because it turns out that some of the abstractions are actually not what I need.

Did you found the one you were looking for?

I am thinking maybe something more declarative could be useful to add.

```rust
expect! {
   "cat",
    -> "hello world\n"
    <- "hello world\r\n"
   session - { ... }
}
```

PS: Sorry I am not sure why I did ignored the issue for this long....

**Comment by zhiburt** [comment]
done
https://docs.rs/expectrl/0.7.0/src/interact_with_callback/interact_with_callback.rs.html#62-68
