### ISSUE TITLE
spawn_bash execute

### ISSUE THREAD

**Issue by Viocalpan** [zhiburt/expectrl#64]
let mut p = spawn_bash().unwrap();
    let hostname = p.execute("ps aux").unwrap();
output:
dpg       1172  0.0  0.0 154828  1448 ?        Ss   08:27   0:00 postgres: logge
dpg       1174  0.0  0.2 302672  4752 ?        Ss   08:27   0:00 postgres: check
dpg       1175  0.0  0.2 302572  4380 ?        Ss   08:27   0:00 postgres: backg
dpg       1176  0.0  0.2 302572  5696 ?        Ss   08:27   0:05 postgres: walwr
dpg       1177  0.0  0.1 303236  2692 ?        Ss   08:27   0:00 postgres: autov
dpg       1178  0.0  0.0 157076  1732 ?        Ss   08:27   0:01 postgres: stats

but in  putty 
dpg       1172  0.0  0.0 154828  1448 ?        Ss   08:27   0:00 postgres: logger
dpg       1174  0.0  0.2 302672  4752 ?        Ss   08:27   0:00 postgres: checkpointer
dpg       1175  0.0  0.2 302572  4644 ?        Ss   08:27   0:00 postgres: background writer
dpg       1176  0.0  0.2 302572  5696 ?        Ss   08:27   0:06 postgres: walwriter
dpg       1177  0.0  0.1 303236  2696 ?        Ss   08:27   0:01 postgres: autovacuum launcher
dpg       1178  0.0  0.0 157076  1732 ?        Ss   08:27   0:02 postgres: stats collector
dpg       1179  0.0  0.1 303108  2240 ?        Ss   08:27   0:00 postgres: logical replication launcher

**Comment by zhiburt** [comment]
Hmmm 

Hi @Viocalpan 

So what you're saying is that the output is cut right?
Very interesting.

I've reproduced it.
Interesting.

Thanks for issuing it.

**Comment by Viocalpan** [comment]
thanks!
but p.execute("ls -la").unwrap();  The output is normal  the cols than 80 over

**Comment by zhiburt** [comment]
> but p.execute("ls -la").unwrap(); The output is normal the cols than 80 over

It's application depended.

So I think it can be closed then?
Reopen it if not.
