### ISSUE TITLE
Support tokio::process::Command?

### ISSUE THREAD

**Issue by baoyachi** [zhiburt/expectrl#66]
See :https://docs.rs/tokio/latest/tokio/process/struct.Command.html

**Comment by zhiburt** [comment]
Hi @baoyachi 

I guess it might be a good proposition to use under the hood to limit blockage.
About `Session::spawn_cmd(...)` maybe also possible, (not sure if type system will allow to).

Though we would be bind to a `tokio`, `async-std` ... which I was trying to mitigate.

PS: Sorry somehow I did not got a notification or what ....
