### ISSUE TITLE
How to send down arrow keys and Enter keys?

### ISSUE THREAD

**Issue by drewstone** [zhiburt/expectrl#72]
I'm unable to properly sending an Enter key click/command or arrow keys (though haven't gotten past just enter first).

Repo - https://github.com/tangle-network/envio-indexer-blueprint/tree/drew/kube
Cmd - `cargo t test_project_lifecycle -- --nocapture`

A snippet of code
```rust
    fn handle_envio_prompt(
        session: &mut Session,
        prompt: &str,
        contracts: &[ContractConfig],
        current_contract_idx: &mut usize,
        current_deployment_idx: &mut usize,
    ) -> Result<(), EnvioError> {
        let send_response = |session: &mut Session, response: &str| -> Result<(), EnvioError> {
            println!("Sending response: {}", response.trim());
            session
                .send_line(response)
                .map_err(|e| EnvioError::ProcessFailed(format!("Failed to send response: {}", e)))
        };

        match prompt.trim() {
            s if s.contains("Specify a folder name") => {
                send_response(session, "\n")?;
            }
```

Results in 
```bash
Processing prompt: ? Specify a folder name (ENTER to skip):  (.)
? Specify a folder name (ENTER to skip):  (.) j
? Specify a folder name (ENTER to skip):  (.) jjj
? Specify a folder name (ENTER to skip):  (.) jjjjj
? Specify a folder name (ENTER to skip):  (.) jjjjjjj
? Specify a folder name (ENTER to skip):  (.) jjjjjjjjj
? Specify a folder name (ENTER to skip):  (.) jjjjjjjjjjj
? Specify a folder name (ENTER to skip):  (.) jjjjjjjjjjjjj
? Specify a folder name (ENTER to skip):  (.) jjjjjjjjjjjjjjj
? Specify a folder name (ENTER to skip):  (.) jjjjjjjjjjjjjjjjj
? Specify a folder name (ENTER to skip):  (.) jjjjjjjjjjjjjjjjjjj
? Specify a folder name (ENTER to skip):  (.) jjjjjjjjjjjjjjjjjjjjj
Sending response:  
```

**Comment by zhiburt** [comment]
Hi @drewstone 

Unfortunately your script does not work with latest `envio` (from master).
There's no longer command `init` etc.

I've run a few own tests with `envio`, and
it seems like it works right? (sometimes)

It's just that it has not standard output.
As I see it expects `\r\n` instead of `\n`?

```rust
session.send("\r\n").unwrap();
```

You could check whether it will help.

And second note here,
Often these CLIs produce a repeated output. (It's because a terminal `echo` mode is turned on).
So you may need to read the whole thing before sending a keystroke.
Like reading a line instead of a regex with `?`.

```rust
Regex(".*\n");
```


Sorry it didn't solved it.
But I hope it helped somehow.

Let me posted if I can help further.

**Comment by drewstone** [comment]
I made some progress with rexpect. Not sure what you mean about envio init not working (it does?) `npm i -g envio`.

Nonetheless, thank you for your help I think `"/r"` is the right approach for enter keys. Do you know what down/up arrow keys would be? I think I'm able to make progress but haven't figured that one out.

**Comment by zhiburt** [comment]
> I made some progress with rexpect.

Interesting to see if there's behavior changes as it is supposed to be quite interchangeble.
By the way you could try to use `async` feature with tokio.

> Not sure what you mean about envio init not working (it does?) npm i -g envio.

Install it from github

> Do you know what down/up arrow keys would be? 

It's seems like these sequences.

```rust
let up = [27, 91, 65];
let down =  [27, 91, 66];
```

**Comment by drewstone** [comment]
Just attempted to use this library, modified things over but tbf it doesn't read things in the same way. Read line actually hangs on the CLI I'm interacting with rather than `rexpect` which allows me to read to exhaustion. I could demo if you're interested.

I'm now mainly stuck with making the program exit properly.
```
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'envio_utils::project::tests::test_project_lifecycle' panicked at src/envio_utils/project.rs:393:14:
called `Result::unwrap()` on an `Err` value: JoinError(JoinError::Panic(Id(1), "could not run `quit` on child process", ...))
test envio_utils::project::tests::test_project_lifecycle ... FAILED
```

I can close this, seems I have figured out the arrow/down keys properly.

In rexpect it is `session.send_control('m')?;` or `CarriageReturn` likely in this library.
For down keys it is `session.send("\x1B[B")?;`
