### ISSUE TITLE
Interact() shows passwords

### ISSUE THREAD

**Issue by GaryBoone** [zhiburt/expectrl#8]
Programs that ask for passwords don't repeat them as they're typed. For example, 

    $ sudo ls
    Password:

but doesn't show the characters typed by the user. Here's a program using `expectrs` to do the same:

    use expectrl::Session;
    use std::process::Command;

    fn main() {
        let mut cmd = Command::new("sudo");
        cmd.arg("ls");
        let mut session = Session::spawn_cmd(cmd).expect("Error while spawning");
        let status = session.interact().expect("Failed to start interact");
        println!("Exit status {:?}", status);
    }

But it repeats whatever is typed.

    Running `target/debug/expectrl_test`
    Password: sdf

In my bash shell, the `Password:` prompt is actually followed by a key symbol, which seems to be a property of bash, not `sudo`.The same effect is seen with `read -s`, which I believe is a bash built-in and might be useful for testing.

**Comment by GaryBoone** [comment]
Looking around for how hiding input is done for password input, I found this: 
https://stackoverflow.com/questions/6856635/hide-password-input-on-terminal

Note that in the code following `Their example of rolling your own`, the `my_getpass()` function turns off echoing to the terminal so that the characters aren't shown. The interact code, as shown here, does echo stdin: https://github.com/zhiburt/ptyprocess/blob/661102bc093312d891feed02aa07e313edd53cf9/src/process.rs#L389. So maybe the bug here is that the `tcsetattr` call done by `getpass` and possibly `sudo` isn't correctly turning off echoing in `ptyprocess`?

**Comment by GaryBoone** [comment]
Possible workaround? If `expectrl` client code could set whether input is echoed to stdin, it could first turn off echoing stdin. Then it would use `try_read_byte()` to read each character. The code could decide whether to write each character to stdout. If it's executing a command that it knows asks for passwords, it could watch for the prompt, then not write those chars to stdout. After it reads the '\n', it would turn echoing back on.

**Comment by zhiburt** [comment]
Essentially this happening because we are doing general reading.

> Possible workaround? If expectrl client code could set whether input is echoed to stdin, it could first turn off echoing stdin. 

Potentially we could provide a function for turning off/on echoing.

So used could turn echo off before `interact` if he/she knows that `sudo` is running of whatever.
Then he/she would return from it turn it back on and that's it.

But do we need to?

I mean you can essentially use a send/write and it won't be echoed (until you want to). 

> Then it would use try_read_byte() to read each character. The code could decide whether to write each character to stdout. If it's executing a command that it knows asks for passwords, it could watch for the prompt, then not write those chars to stdout. After it reads the '\n', it would turn echoing back on.

I don't think it's a right way to do so.

**Comment by zhiburt** [comment]
Actually we could (potentially) to inherit terminal state on each read from `stdin`.
Which seems to me will work.

But one more time I am not sure if it any useful

**Comment by zhiburt** [comment]
```rust
use expectrl::repl::spawn_bash;

#[cfg(feature = "sync")]
fn main() {
    use std::io::BufRead;

    let mut bash = spawn_bash().expect("Error while spawning bash");
    bash.send_line("sudo ls").unwrap();
    bash.send_line("123123").unwrap();

    let mut line = String::new();
    bash.read_line(&mut line).unwrap();
    bash.read_line(&mut line).unwrap();

    println!("Now you're in interacting mode");
    println!("{}", line);
}
```

### output

```
Now you're in interacting mode
[sudo] password for mzhiburt: 
Sorry, try again.
```

**Comment by zhiburt** [comment]
> Actually we could (potentially) inherit terminal state of child and change our terminal on each read from stdin. And at the end restore original state.
Which seems to me will work.

Verified it doesn't work as expected.

**Comment by zhiburt** [comment]
I started to think it may be cool to implement.

**Comment by GaryBoone** [comment]
> Potentially we could provide a function for turning off/on echoing.
> But do we need to?

Ideally, no. Ideally, the interactive mode would allow the command being run to work like normal. The `expectrl` client shouldn't need to do anything but start the cmd and enter the interactive mode. Then the user should see the prompt and type the password without echo, just like it works in a normal terminal today. My suggestion was meant a possible workaround until a solution is found or if a solution can't be found.

I think another question would be, should the `expectrl` client code be able to read the unechoed response? In my case, no: It's for the command (eg "sudo ls"), not for my client code. It would be more secure to not read it. But if you were writing password managing code, you would need to be able to read it.

**Comment by zhiburt** [comment]
It's supposed to be done f251b6264fa31049cba8a792a25d98b0c0cd238e

**Comment by zhiburt** [comment]
Please verify it and if it is close the issue.

**Comment by zhiburt** [comment]
I want to say thank you one more time as it turns out a good feature (fix).

**Comment by zhiburt** [comment]
Can I ask you to run one test?
Because CI is continuously fails even though on my machine is OK.

8b7307f07e60463fab8ff6c3263131f4b0353b8f

**Comment by zhiburt** [comment]
I fixed ubuntu issue on CI but after this macos issue appeard... :disappointed: 

I have no idea why my investigation is rendered in a comment here

https://github.com/zhiburt/ptyprocess/blob/970b810b77aa9f5d66fa554bf8a80c9f34aa7748/src/process.rs#L402-L410

The fanny thing is that async version works even though they are identical.... (almost)

**Comment by GaryBoone** [comment]
Results with the latest code:

1. I tried this code above: https://github.com/zhiburt/expectrl/issues/8#issuecomment-885723278
The password was _not_ repeated. But that code doesn't enter `interact()`.

2. I tried the original code at the top of this issue. It _does_ repeat the password.

    Cargo.toml:
    expectrl = {git = "https://github.com/zhiburt/expectrl"}
    ptyprocess ={git = "https://github.com/zhiburt/ptyprocess"}


    $ cargo update; cargo clean; cargo run
        Updating git repository `https://github.com/zhiburt/expectrl`
        Updating git repository `https://github.com/zhiburt/ptyprocess`
        Updating crates.io index
        Updating ptyprocess v0.1.8 (https://github.com/zhiburt/ptyprocess#849d8f37) -> #970b810b
    ...
    Compiling ptyprocess v0.1.7
    Compiling ptyprocess v0.1.8 (https://github.com/zhiburt/ptyprocess#970b810b)
    Compiling expectrl v0.1.2 (https://github.com/zhiburt/expectrl#30a45f0b)
    Compiling expectrl_test v0.1.0 (/Users/gboone/GoogleDrive/development/rust/expectrl_test)
    ...
        Finished dev [unoptimized + debuginfo] target(s) in 12.03s
        Running `target/debug/expectrl_test`
    Password: asd

    Sorry, try again.
    Password: ^C

3. On macOs:

    $ cargo test end_of_interact
    ...
         Running tests/io.rs (target/debug/deps/io-5295b8535fb91984)

    running 1 test
    Cargo.lock	LICENSE		examples	target
    Cargo.toml	README.md	src		tests
    Cargo.lock	LICENSE		examples	target
    Cargo.toml	README.md	src		tests
    test end_of_interact ... ok

    test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 18 filtered out; finished in 0.01s

So given, #2, the issue does not appear to be fixed, unless there's a different way `interact()` should be used than:

    let mut cmd = Command::new("sudo");
    cmd.arg("ls");
    let mut session = Session::spawn_cmd(cmd).expect("Error while spawning");
    let status = session.interact().expect("Failed to start interact");
    println!("Exit status {:?}", status);

**Comment by GaryBoone** [comment]
Repeated #3, `$ cargo test end_of_interact` on an Ubuntu-based system. Same result. Passed.

Repeated #1 on an Ubuntu-based system. Same result: with `interact()`, the password was shown.

**Comment by zhiburt** [comment]
That's surprising to me that on CI macos test's are failing (for sync version but not async) so I decided to ignore them fore now....

You can use the latest `expectrl` to run this. And it suppose work as expected.

```rust
fn main() {
    let mut bash = expectrl::Session::spawn("bash").unwrap();

    println!("Now you're in interacting mode");
    println!("To return control back to main type CTRL-]");

    let status = bash.interact().expect("Failed to start interact");

    println!("Quiting status {:?}", status);
}
```

* While developing found one question with EOF handling https://github.com/zhiburt/ptyprocess/issues/6
* And `spawn_bash` function acts not as I would expect I probably try to fix it tomorrow.

**Comment by zhiburt** [comment]
And yes thanks for your tests 👍

**Comment by GaryBoone** [comment]
Success! My original example at the top, which starts the `sudo ls` command, then enters interactive mode so the user can type the password, behaved as expected, including with exit codes and when hitting ctrl-]. Your code example two comments up also worked for me to start an interactive bash without printing the password back to the screen.

I'll do some more testing, then close this bug.

**Comment by GaryBoone** [comment]
My tests show stdin echoing now working as expected. Closing. Will we have a release with these changes? Thanks, Maxim!

**Comment by zhiburt** [comment]
>  Will we have a release with these changes? 

Yes,
But I am trying to solve 1 issue related to spawning bash. #3 
And it a bit related to this issue.
After I am done I'll release a new version.

**Comment by GaryBoone** [comment]
I have observed that interact() sometimes returns the `still running` status after a command finished. I haven't been able to create a repro example though. It's easily worked around by following with a `process.wait()`. I'll create a bug if I can, so FYI atm.

**Comment by zhiburt** [comment]
Hi @GaryBoone

> I have observed that interact() sometimes returns the still running status after a command finished. I haven't been able to create a repro example though. It's easily worked around by following with a process.wait(). I'll create a bug if I can, so FYI atm.

That's true that happens sometime and this is not a bug. (At least the case that I am aware off)
See this test.

https://github.com/zhiburt/ptyprocess/blob/d6a6380aba1012e34415329b4d7456edfa9fd9c5/tests/io.rs#L412-L432

It happens because sometimes we reach EOF earlier than process exits.

Do you think I need update the document comment?

**Comment by GaryBoone** [comment]
I see. Makes sense. The comment in that test is clear, but I would suggest adding something like:

    // To be sure the process has completed, you can explicitly wait:
    status = process.wait()
